# fly.toml app configuration file generated for telegraf on 2023-05-30T10:23:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "filcdn-telegraf"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  CALIBRATION_FILBEAM_CONTROLLER_WALLET = "0x63C3e7c561cB6951e8749bE5109c321f1259afc7"
  MAINNET_FILBEAM_CONTROLLER_WALLET = "0x63C3e7c561cB6951e8749bE5109c321f1259afc7"
